name: "protocol_compose_stack"

services:
  orchestrator:
    environment:
      RUST_SERVICE_URL: http://rust_service:3000
      SCENARIOS_DIR: /app/benchmarks/scenarios
    build:
      context: ..
      dockerfile: infra/docker/orchestrator.Dockerfile
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - benchmark_net
  rust_service:
    build:
      context: ..
      dockerfile: infra/docker/rust.Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - benchmark_net

networks:
  benchmark_net:
